version: 2

archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make tfgen
builds:
  - goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    env:
      - CGO_ENABLED=0
    dir: ./provider
    main: ./cmd/pulumi-resource-materialize
    binary: pulumi-resource-materialize
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/MaterializeInc/pulumi-materialize/provider/pkg/version.Version={{.Tag }}
changelog:
  disable: true
