// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Materialize
{
    /// <summary>
    /// The connection resource allows you to manage connections in Materialize.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using Pulumi;
    /// using Materialize = Pulumi.Materialize;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Create a Confluent Schema Registry Connection
    ///     var exampleConfluentSchemaRegistryConnection = new Materialize.ConnectionConfluentSchemaRegistry("exampleConfluentSchemaRegistryConnection", new()
    ///     {
    ///         Password = new Materialize.Inputs.ConnectionConfluentSchemaRegistryPasswordArgs
    ///         {
    ///             DatabaseName = "database",
    ///             Name = "example",
    ///             SchemaName = "schema",
    ///         },
    ///         Url = "https://rp-f00000bar.data.vectorized.cloud:30993",
    ///         Username = new Materialize.Inputs.ConnectionConfluentSchemaRegistryUsernameArgs
    ///         {
    ///             Text = "example",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// #Connections can be imported using the connection id
    /// 
    /// ```sh
    ///  $ pulumi import materialize:index/connectionConfluentSchemaRegistry:ConnectionConfluentSchemaRegistry example &lt;connection_id&gt;
    /// ```
    /// </summary>
    [MaterializeResourceType("materialize:index/connectionConfluentSchemaRegistry:ConnectionConfluentSchemaRegistry")]
    public partial class ConnectionConfluentSchemaRegistry : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The AWS PrivateLink configuration for the Confluent Schema Registry.
        /// </summary>
        [Output("awsPrivatelink")]
        public Output<Outputs.ConnectionConfluentSchemaRegistryAwsPrivatelink?> AwsPrivatelink { get; private set; } = null!;

        /// <summary>
        /// The type of connection.
        /// </summary>
        [Output("connectionType")]
        public Output<string> ConnectionType { get; private set; } = null!;

        /// <summary>
        /// The identifier for the connection database.
        /// </summary>
        [Output("databaseName")]
        public Output<string?> DatabaseName { get; private set; } = null!;

        /// <summary>
        /// The identifier for the connection.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The password for the Confluent Schema Registry.
        /// </summary>
        [Output("password")]
        public Output<Outputs.ConnectionConfluentSchemaRegistryPassword?> Password { get; private set; } = null!;

        /// <summary>
        /// The fully qualified name of the connection.
        /// </summary>
        [Output("qualifiedSqlName")]
        public Output<string> QualifiedSqlName { get; private set; } = null!;

        /// <summary>
        /// The identifier for the connection schema.
        /// </summary>
        [Output("schemaName")]
        public Output<string?> SchemaName { get; private set; } = null!;

        /// <summary>
        /// The SSH tunnel configuration for the Confluent Schema Registry.
        /// </summary>
        [Output("sshTunnel")]
        public Output<Outputs.ConnectionConfluentSchemaRegistrySshTunnel?> SshTunnel { get; private set; } = null!;

        /// <summary>
        /// The client certificate for the Confluent Schema Registry.
        /// </summary>
        [Output("sslCertificate")]
        public Output<Outputs.ConnectionConfluentSchemaRegistrySslCertificate?> SslCertificate { get; private set; } = null!;

        /// <summary>
        /// The CA certificate for the Confluent Schema Registry.
        /// </summary>
        [Output("sslCertificateAuthority")]
        public Output<Outputs.ConnectionConfluentSchemaRegistrySslCertificateAuthority?> SslCertificateAuthority { get; private set; } = null!;

        /// <summary>
        /// The client key for the Confluent Schema Registry.
        /// </summary>
        [Output("sslKey")]
        public Output<Outputs.ConnectionConfluentSchemaRegistrySslKey?> SslKey { get; private set; } = null!;

        /// <summary>
        /// The URL of the Confluent Schema Registry.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;

        /// <summary>
        /// The username for the Confluent Schema Registry.
        /// </summary>
        [Output("username")]
        public Output<Outputs.ConnectionConfluentSchemaRegistryUsername?> Username { get; private set; } = null!;


        /// <summary>
        /// Create a ConnectionConfluentSchemaRegistry resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ConnectionConfluentSchemaRegistry(string name, ConnectionConfluentSchemaRegistryArgs args, CustomResourceOptions? options = null)
            : base("materialize:index/connectionConfluentSchemaRegistry:ConnectionConfluentSchemaRegistry", name, args ?? new ConnectionConfluentSchemaRegistryArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ConnectionConfluentSchemaRegistry(string name, Input<string> id, ConnectionConfluentSchemaRegistryState? state = null, CustomResourceOptions? options = null)
            : base("materialize:index/connectionConfluentSchemaRegistry:ConnectionConfluentSchemaRegistry", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/MaterializeInc/pulumi-materialize",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ConnectionConfluentSchemaRegistry resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ConnectionConfluentSchemaRegistry Get(string name, Input<string> id, ConnectionConfluentSchemaRegistryState? state = null, CustomResourceOptions? options = null)
        {
            return new ConnectionConfluentSchemaRegistry(name, id, state, options);
        }
    }

    public sealed class ConnectionConfluentSchemaRegistryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The AWS PrivateLink configuration for the Confluent Schema Registry.
        /// </summary>
        [Input("awsPrivatelink")]
        public Input<Inputs.ConnectionConfluentSchemaRegistryAwsPrivatelinkArgs>? AwsPrivatelink { get; set; }

        /// <summary>
        /// The identifier for the connection database.
        /// </summary>
        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        /// <summary>
        /// The identifier for the connection.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The password for the Confluent Schema Registry.
        /// </summary>
        [Input("password")]
        public Input<Inputs.ConnectionConfluentSchemaRegistryPasswordArgs>? Password { get; set; }

        /// <summary>
        /// The identifier for the connection schema.
        /// </summary>
        [Input("schemaName")]
        public Input<string>? SchemaName { get; set; }

        /// <summary>
        /// The SSH tunnel configuration for the Confluent Schema Registry.
        /// </summary>
        [Input("sshTunnel")]
        public Input<Inputs.ConnectionConfluentSchemaRegistrySshTunnelArgs>? SshTunnel { get; set; }

        /// <summary>
        /// The client certificate for the Confluent Schema Registry.
        /// </summary>
        [Input("sslCertificate")]
        public Input<Inputs.ConnectionConfluentSchemaRegistrySslCertificateArgs>? SslCertificate { get; set; }

        /// <summary>
        /// The CA certificate for the Confluent Schema Registry.
        /// </summary>
        [Input("sslCertificateAuthority")]
        public Input<Inputs.ConnectionConfluentSchemaRegistrySslCertificateAuthorityArgs>? SslCertificateAuthority { get; set; }

        /// <summary>
        /// The client key for the Confluent Schema Registry.
        /// </summary>
        [Input("sslKey")]
        public Input<Inputs.ConnectionConfluentSchemaRegistrySslKeyArgs>? SslKey { get; set; }

        /// <summary>
        /// The URL of the Confluent Schema Registry.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        /// <summary>
        /// The username for the Confluent Schema Registry.
        /// </summary>
        [Input("username")]
        public Input<Inputs.ConnectionConfluentSchemaRegistryUsernameArgs>? Username { get; set; }

        public ConnectionConfluentSchemaRegistryArgs()
        {
        }
        public static new ConnectionConfluentSchemaRegistryArgs Empty => new ConnectionConfluentSchemaRegistryArgs();
    }

    public sealed class ConnectionConfluentSchemaRegistryState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The AWS PrivateLink configuration for the Confluent Schema Registry.
        /// </summary>
        [Input("awsPrivatelink")]
        public Input<Inputs.ConnectionConfluentSchemaRegistryAwsPrivatelinkGetArgs>? AwsPrivatelink { get; set; }

        /// <summary>
        /// The type of connection.
        /// </summary>
        [Input("connectionType")]
        public Input<string>? ConnectionType { get; set; }

        /// <summary>
        /// The identifier for the connection database.
        /// </summary>
        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        /// <summary>
        /// The identifier for the connection.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The password for the Confluent Schema Registry.
        /// </summary>
        [Input("password")]
        public Input<Inputs.ConnectionConfluentSchemaRegistryPasswordGetArgs>? Password { get; set; }

        /// <summary>
        /// The fully qualified name of the connection.
        /// </summary>
        [Input("qualifiedSqlName")]
        public Input<string>? QualifiedSqlName { get; set; }

        /// <summary>
        /// The identifier for the connection schema.
        /// </summary>
        [Input("schemaName")]
        public Input<string>? SchemaName { get; set; }

        /// <summary>
        /// The SSH tunnel configuration for the Confluent Schema Registry.
        /// </summary>
        [Input("sshTunnel")]
        public Input<Inputs.ConnectionConfluentSchemaRegistrySshTunnelGetArgs>? SshTunnel { get; set; }

        /// <summary>
        /// The client certificate for the Confluent Schema Registry.
        /// </summary>
        [Input("sslCertificate")]
        public Input<Inputs.ConnectionConfluentSchemaRegistrySslCertificateGetArgs>? SslCertificate { get; set; }

        /// <summary>
        /// The CA certificate for the Confluent Schema Registry.
        /// </summary>
        [Input("sslCertificateAuthority")]
        public Input<Inputs.ConnectionConfluentSchemaRegistrySslCertificateAuthorityGetArgs>? SslCertificateAuthority { get; set; }

        /// <summary>
        /// The client key for the Confluent Schema Registry.
        /// </summary>
        [Input("sslKey")]
        public Input<Inputs.ConnectionConfluentSchemaRegistrySslKeyGetArgs>? SslKey { get; set; }

        /// <summary>
        /// The URL of the Confluent Schema Registry.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        /// <summary>
        /// The username for the Confluent Schema Registry.
        /// </summary>
        [Input("username")]
        public Input<Inputs.ConnectionConfluentSchemaRegistryUsernameGetArgs>? Username { get; set; }

        public ConnectionConfluentSchemaRegistryState()
        {
        }
        public static new ConnectionConfluentSchemaRegistryState Empty => new ConnectionConfluentSchemaRegistryState();
    }
}
