// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Materialize
{
    public static class GetClusterReplicas
    {
        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Materialize = Pulumi.Materialize;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Materialize.GetClusterReplicas.Invoke();
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetClusterReplicasResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetClusterReplicasResult>("materialize:index/getClusterReplicas:GetClusterReplicas", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetClusterReplicasResult
    {
        /// <summary>
        /// The cluster replicas in the account
        /// </summary>
        public readonly ImmutableArray<Outputs.GetClusterReplicasClusterReplicaResult> ClusterReplicas;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetClusterReplicasResult(
            ImmutableArray<Outputs.GetClusterReplicasClusterReplicaResult> clusterReplicas,

            string id)
        {
            ClusterReplicas = clusterReplicas;
            Id = id;
        }
    }
}
