// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Materialize
{
    public static class GetIndexes
    {
        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Materialize = Pulumi.Materialize;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Materialize.GetIndexes.Invoke();
        /// 
        ///     var materialize = Materialize.GetIndexes.Invoke(new()
        ///     {
        ///         DatabaseName = "materialize",
        ///     });
        /// 
        ///     var materializeSchema = Materialize.GetIndexes.Invoke(new()
        ///     {
        ///         DatabaseName = "materialize",
        ///         SchemaName = "schema",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetIndexesResult> InvokeAsync(GetIndexesArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetIndexesResult>("materialize:index/getIndexes:GetIndexes", args ?? new GetIndexesArgs(), options.WithDefaults());

        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Materialize = Pulumi.Materialize;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Materialize.GetIndexes.Invoke();
        /// 
        ///     var materialize = Materialize.GetIndexes.Invoke(new()
        ///     {
        ///         DatabaseName = "materialize",
        ///     });
        /// 
        ///     var materializeSchema = Materialize.GetIndexes.Invoke(new()
        ///     {
        ///         DatabaseName = "materialize",
        ///         SchemaName = "schema",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetIndexesResult> Invoke(GetIndexesInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetIndexesResult>("materialize:index/getIndexes:GetIndexes", args ?? new GetIndexesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetIndexesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Limit indexes to a specific database
        /// </summary>
        [Input("databaseName")]
        public string? DatabaseName { get; set; }

        /// <summary>
        /// Limit indexes to a specific schema within a specific database
        /// </summary>
        [Input("schemaName")]
        public string? SchemaName { get; set; }

        public GetIndexesArgs()
        {
        }
        public static new GetIndexesArgs Empty => new GetIndexesArgs();
    }

    public sealed class GetIndexesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Limit indexes to a specific database
        /// </summary>
        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        /// <summary>
        /// Limit indexes to a specific schema within a specific database
        /// </summary>
        [Input("schemaName")]
        public Input<string>? SchemaName { get; set; }

        public GetIndexesInvokeArgs()
        {
        }
        public static new GetIndexesInvokeArgs Empty => new GetIndexesInvokeArgs();
    }


    [OutputType]
    public sealed class GetIndexesResult
    {
        /// <summary>
        /// Limit indexes to a specific database
        /// </summary>
        public readonly string? DatabaseName;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The indexes in the account
        /// </summary>
        public readonly ImmutableArray<Outputs.GetIndexesIndexResult> Indexes;
        /// <summary>
        /// Limit indexes to a specific schema within a specific database
        /// </summary>
        public readonly string? SchemaName;

        [OutputConstructor]
        private GetIndexesResult(
            string? databaseName,

            string id,

            ImmutableArray<Outputs.GetIndexesIndexResult> indexes,

            string? schemaName)
        {
            DatabaseName = databaseName;
            Id = id;
            Indexes = indexes;
            SchemaName = schemaName;
        }
    }
}
