// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Materialize
{
    /// <summary>
    /// A materialized view persists in durable storage and can be written to, updated and seamlessly joined with other views, views or sources.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using Pulumi;
    /// using Materialize = Pulumi.Materialize;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var simpleMaterializedViewMaterializedView = new Materialize.MaterializedView("simpleMaterializedViewMaterializedView", new()
    ///     {
    ///         SchemaName = materialize_schema.Schema.Name,
    ///         DatabaseName = materialize_database.Database.Name,
    ///         Statement = @$"SELECT
    ///     *
    /// FROM
    ///     {materialize_table.Simple_table.Qualified_name}
    /// ",
    ///     }, new CustomResourceOptions
    ///     {
    ///         DependsOn = new[]
    ///         {
    ///             materialize_table.Simple_table,
    ///         },
    ///     });
    /// 
    ///     var simpleMaterializedViewIndex_materializedViewMaterializedView = new Materialize.MaterializedView("simpleMaterializedViewIndex/materializedViewMaterializedView", new()
    ///     {
    ///         SchemaName = materialize_schema.Schema.Name,
    ///         DatabaseName = materialize_database.Database.Name,
    ///         Statement = "SELECT * FROM materialize.public.simple_table",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// # Materialized views can be imported using the source id
    /// 
    /// ```sh
    ///  $ pulumi import materialize:index/materializedView:MaterializedView example_materialize_view &lt;view_id&gt;
    /// ```
    /// </summary>
    [MaterializeResourceType("materialize:index/materializedView:MaterializedView")]
    public partial class MaterializedView : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The cluster to maintain the materialized view. If not specified, defaults to the default cluster.
        /// </summary>
        [Output("clusterName")]
        public Output<string?> ClusterName { get; private set; } = null!;

        /// <summary>
        /// The identifier for the materialized view database.
        /// </summary>
        [Output("databaseName")]
        public Output<string?> DatabaseName { get; private set; } = null!;

        /// <summary>
        /// The identifier for the materialized view.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The fully qualified name of the materialized view.
        /// </summary>
        [Output("qualifiedSqlName")]
        public Output<string> QualifiedSqlName { get; private set; } = null!;

        /// <summary>
        /// The identifier for the materialized view schema.
        /// </summary>
        [Output("schemaName")]
        public Output<string?> SchemaName { get; private set; } = null!;

        /// <summary>
        /// The SQL statement to create the materialized view.
        /// </summary>
        [Output("statement")]
        public Output<string> Statement { get; private set; } = null!;


        /// <summary>
        /// Create a MaterializedView resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MaterializedView(string name, MaterializedViewArgs args, CustomResourceOptions? options = null)
            : base("materialize:index/materializedView:MaterializedView", name, args ?? new MaterializedViewArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MaterializedView(string name, Input<string> id, MaterializedViewState? state = null, CustomResourceOptions? options = null)
            : base("materialize:index/materializedView:MaterializedView", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/MaterializeInc/pulumi-materialize",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MaterializedView resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MaterializedView Get(string name, Input<string> id, MaterializedViewState? state = null, CustomResourceOptions? options = null)
        {
            return new MaterializedView(name, id, state, options);
        }
    }

    public sealed class MaterializedViewArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The cluster to maintain the materialized view. If not specified, defaults to the default cluster.
        /// </summary>
        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        /// <summary>
        /// The identifier for the materialized view database.
        /// </summary>
        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        /// <summary>
        /// The identifier for the materialized view.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The identifier for the materialized view schema.
        /// </summary>
        [Input("schemaName")]
        public Input<string>? SchemaName { get; set; }

        /// <summary>
        /// The SQL statement to create the materialized view.
        /// </summary>
        [Input("statement", required: true)]
        public Input<string> Statement { get; set; } = null!;

        public MaterializedViewArgs()
        {
        }
        public static new MaterializedViewArgs Empty => new MaterializedViewArgs();
    }

    public sealed class MaterializedViewState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The cluster to maintain the materialized view. If not specified, defaults to the default cluster.
        /// </summary>
        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        /// <summary>
        /// The identifier for the materialized view database.
        /// </summary>
        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        /// <summary>
        /// The identifier for the materialized view.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The fully qualified name of the materialized view.
        /// </summary>
        [Input("qualifiedSqlName")]
        public Input<string>? QualifiedSqlName { get; set; }

        /// <summary>
        /// The identifier for the materialized view schema.
        /// </summary>
        [Input("schemaName")]
        public Input<string>? SchemaName { get; set; }

        /// <summary>
        /// The SQL statement to create the materialized view.
        /// </summary>
        [Input("statement")]
        public Input<string>? Statement { get; set; }

        public MaterializedViewState()
        {
        }
        public static new MaterializedViewState Empty => new MaterializedViewState();
    }
}
