# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ConnectionPostgresArgs', 'ConnectionPostgres']

@pulumi.input_type
class ConnectionPostgresArgs:
    def __init__(__self__, *,
                 database: pulumi.Input[str],
                 host: pulumi.Input[str],
                 user: pulumi.Input['ConnectionPostgresUserArgs'],
                 aws_privatelink: Optional[pulumi.Input['ConnectionPostgresAwsPrivatelinkArgs']] = None,
                 database_name: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input['ConnectionPostgresPasswordArgs']] = None,
                 port: Optional[pulumi.Input[int]] = None,
                 schema_name: Optional[pulumi.Input[str]] = None,
                 ssh_tunnel: Optional[pulumi.Input['ConnectionPostgresSshTunnelArgs']] = None,
                 ssl_certificate: Optional[pulumi.Input['ConnectionPostgresSslCertificateArgs']] = None,
                 ssl_certificate_authority: Optional[pulumi.Input['ConnectionPostgresSslCertificateAuthorityArgs']] = None,
                 ssl_key: Optional[pulumi.Input['ConnectionPostgresSslKeyArgs']] = None,
                 ssl_mode: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a ConnectionPostgres resource.
        :param pulumi.Input[str] database: The target Postgres database.
        :param pulumi.Input[str] host: The Postgres database hostname.
        :param pulumi.Input['ConnectionPostgresUserArgs'] user: The Postgres database username.
        :param pulumi.Input['ConnectionPostgresAwsPrivatelinkArgs'] aws_privatelink: The AWS PrivateLink configuration for the Postgres database.
        :param pulumi.Input[str] database_name: The identifier for the connection database.
        :param pulumi.Input[str] name: The identifier for the connection.
        :param pulumi.Input['ConnectionPostgresPasswordArgs'] password: The Postgres database password.
        :param pulumi.Input[int] port: The Postgres database port.
        :param pulumi.Input[str] schema_name: The identifier for the connection schema.
        :param pulumi.Input['ConnectionPostgresSshTunnelArgs'] ssh_tunnel: The SSH tunnel configuration for the Postgres database.
        :param pulumi.Input['ConnectionPostgresSslCertificateArgs'] ssl_certificate: The client certificate for the Postgres database.
        :param pulumi.Input['ConnectionPostgresSslCertificateAuthorityArgs'] ssl_certificate_authority: The CA certificate for the Postgres database.
        :param pulumi.Input['ConnectionPostgresSslKeyArgs'] ssl_key: The client key for the Postgres database.
        :param pulumi.Input[str] ssl_mode: The SSL mode for the Postgres database.
        """
        pulumi.set(__self__, "database", database)
        pulumi.set(__self__, "host", host)
        pulumi.set(__self__, "user", user)
        if aws_privatelink is not None:
            pulumi.set(__self__, "aws_privatelink", aws_privatelink)
        if database_name is not None:
            pulumi.set(__self__, "database_name", database_name)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if schema_name is not None:
            pulumi.set(__self__, "schema_name", schema_name)
        if ssh_tunnel is not None:
            pulumi.set(__self__, "ssh_tunnel", ssh_tunnel)
        if ssl_certificate is not None:
            pulumi.set(__self__, "ssl_certificate", ssl_certificate)
        if ssl_certificate_authority is not None:
            pulumi.set(__self__, "ssl_certificate_authority", ssl_certificate_authority)
        if ssl_key is not None:
            pulumi.set(__self__, "ssl_key", ssl_key)
        if ssl_mode is not None:
            pulumi.set(__self__, "ssl_mode", ssl_mode)

    @property
    @pulumi.getter
    def database(self) -> pulumi.Input[str]:
        """
        The target Postgres database.
        """
        return pulumi.get(self, "database")

    @database.setter
    def database(self, value: pulumi.Input[str]):
        pulumi.set(self, "database", value)

    @property
    @pulumi.getter
    def host(self) -> pulumi.Input[str]:
        """
        The Postgres database hostname.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: pulumi.Input[str]):
        pulumi.set(self, "host", value)

    @property
    @pulumi.getter
    def user(self) -> pulumi.Input['ConnectionPostgresUserArgs']:
        """
        The Postgres database username.
        """
        return pulumi.get(self, "user")

    @user.setter
    def user(self, value: pulumi.Input['ConnectionPostgresUserArgs']):
        pulumi.set(self, "user", value)

    @property
    @pulumi.getter(name="awsPrivatelink")
    def aws_privatelink(self) -> Optional[pulumi.Input['ConnectionPostgresAwsPrivatelinkArgs']]:
        """
        The AWS PrivateLink configuration for the Postgres database.
        """
        return pulumi.get(self, "aws_privatelink")

    @aws_privatelink.setter
    def aws_privatelink(self, value: Optional[pulumi.Input['ConnectionPostgresAwsPrivatelinkArgs']]):
        pulumi.set(self, "aws_privatelink", value)

    @property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> Optional[pulumi.Input[str]]:
        """
        The identifier for the connection database.
        """
        return pulumi.get(self, "database_name")

    @database_name.setter
    def database_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "database_name", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The identifier for the connection.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input['ConnectionPostgresPasswordArgs']]:
        """
        The Postgres database password.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input['ConnectionPostgresPasswordArgs']]):
        pulumi.set(self, "password", value)

    @property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[int]]:
        """
        The Postgres database port.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "port", value)

    @property
    @pulumi.getter(name="schemaName")
    def schema_name(self) -> Optional[pulumi.Input[str]]:
        """
        The identifier for the connection schema.
        """
        return pulumi.get(self, "schema_name")

    @schema_name.setter
    def schema_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "schema_name", value)

    @property
    @pulumi.getter(name="sshTunnel")
    def ssh_tunnel(self) -> Optional[pulumi.Input['ConnectionPostgresSshTunnelArgs']]:
        """
        The SSH tunnel configuration for the Postgres database.
        """
        return pulumi.get(self, "ssh_tunnel")

    @ssh_tunnel.setter
    def ssh_tunnel(self, value: Optional[pulumi.Input['ConnectionPostgresSshTunnelArgs']]):
        pulumi.set(self, "ssh_tunnel", value)

    @property
    @pulumi.getter(name="sslCertificate")
    def ssl_certificate(self) -> Optional[pulumi.Input['ConnectionPostgresSslCertificateArgs']]:
        """
        The client certificate for the Postgres database.
        """
        return pulumi.get(self, "ssl_certificate")

    @ssl_certificate.setter
    def ssl_certificate(self, value: Optional[pulumi.Input['ConnectionPostgresSslCertificateArgs']]):
        pulumi.set(self, "ssl_certificate", value)

    @property
    @pulumi.getter(name="sslCertificateAuthority")
    def ssl_certificate_authority(self) -> Optional[pulumi.Input['ConnectionPostgresSslCertificateAuthorityArgs']]:
        """
        The CA certificate for the Postgres database.
        """
        return pulumi.get(self, "ssl_certificate_authority")

    @ssl_certificate_authority.setter
    def ssl_certificate_authority(self, value: Optional[pulumi.Input['ConnectionPostgresSslCertificateAuthorityArgs']]):
        pulumi.set(self, "ssl_certificate_authority", value)

    @property
    @pulumi.getter(name="sslKey")
    def ssl_key(self) -> Optional[pulumi.Input['ConnectionPostgresSslKeyArgs']]:
        """
        The client key for the Postgres database.
        """
        return pulumi.get(self, "ssl_key")

    @ssl_key.setter
    def ssl_key(self, value: Optional[pulumi.Input['ConnectionPostgresSslKeyArgs']]):
        pulumi.set(self, "ssl_key", value)

    @property
    @pulumi.getter(name="sslMode")
    def ssl_mode(self) -> Optional[pulumi.Input[str]]:
        """
        The SSL mode for the Postgres database.
        """
        return pulumi.get(self, "ssl_mode")

    @ssl_mode.setter
    def ssl_mode(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "ssl_mode", value)


@pulumi.input_type
class _ConnectionPostgresState:
    def __init__(__self__, *,
                 aws_privatelink: Optional[pulumi.Input['ConnectionPostgresAwsPrivatelinkArgs']] = None,
                 connection_type: Optional[pulumi.Input[str]] = None,
                 database: Optional[pulumi.Input[str]] = None,
                 database_name: Optional[pulumi.Input[str]] = None,
                 host: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input['ConnectionPostgresPasswordArgs']] = None,
                 port: Optional[pulumi.Input[int]] = None,
                 qualified_sql_name: Optional[pulumi.Input[str]] = None,
                 schema_name: Optional[pulumi.Input[str]] = None,
                 ssh_tunnel: Optional[pulumi.Input['ConnectionPostgresSshTunnelArgs']] = None,
                 ssl_certificate: Optional[pulumi.Input['ConnectionPostgresSslCertificateArgs']] = None,
                 ssl_certificate_authority: Optional[pulumi.Input['ConnectionPostgresSslCertificateAuthorityArgs']] = None,
                 ssl_key: Optional[pulumi.Input['ConnectionPostgresSslKeyArgs']] = None,
                 ssl_mode: Optional[pulumi.Input[str]] = None,
                 user: Optional[pulumi.Input['ConnectionPostgresUserArgs']] = None):
        """
        Input properties used for looking up and filtering ConnectionPostgres resources.
        :param pulumi.Input['ConnectionPostgresAwsPrivatelinkArgs'] aws_privatelink: The AWS PrivateLink configuration for the Postgres database.
        :param pulumi.Input[str] connection_type: The type of connection.
        :param pulumi.Input[str] database: The target Postgres database.
        :param pulumi.Input[str] database_name: The identifier for the connection database.
        :param pulumi.Input[str] host: The Postgres database hostname.
        :param pulumi.Input[str] name: The identifier for the connection.
        :param pulumi.Input['ConnectionPostgresPasswordArgs'] password: The Postgres database password.
        :param pulumi.Input[int] port: The Postgres database port.
        :param pulumi.Input[str] qualified_sql_name: The fully qualified name of the connection.
        :param pulumi.Input[str] schema_name: The identifier for the connection schema.
        :param pulumi.Input['ConnectionPostgresSshTunnelArgs'] ssh_tunnel: The SSH tunnel configuration for the Postgres database.
        :param pulumi.Input['ConnectionPostgresSslCertificateArgs'] ssl_certificate: The client certificate for the Postgres database.
        :param pulumi.Input['ConnectionPostgresSslCertificateAuthorityArgs'] ssl_certificate_authority: The CA certificate for the Postgres database.
        :param pulumi.Input['ConnectionPostgresSslKeyArgs'] ssl_key: The client key for the Postgres database.
        :param pulumi.Input[str] ssl_mode: The SSL mode for the Postgres database.
        :param pulumi.Input['ConnectionPostgresUserArgs'] user: The Postgres database username.
        """
        if aws_privatelink is not None:
            pulumi.set(__self__, "aws_privatelink", aws_privatelink)
        if connection_type is not None:
            pulumi.set(__self__, "connection_type", connection_type)
        if database is not None:
            pulumi.set(__self__, "database", database)
        if database_name is not None:
            pulumi.set(__self__, "database_name", database_name)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if qualified_sql_name is not None:
            pulumi.set(__self__, "qualified_sql_name", qualified_sql_name)
        if schema_name is not None:
            pulumi.set(__self__, "schema_name", schema_name)
        if ssh_tunnel is not None:
            pulumi.set(__self__, "ssh_tunnel", ssh_tunnel)
        if ssl_certificate is not None:
            pulumi.set(__self__, "ssl_certificate", ssl_certificate)
        if ssl_certificate_authority is not None:
            pulumi.set(__self__, "ssl_certificate_authority", ssl_certificate_authority)
        if ssl_key is not None:
            pulumi.set(__self__, "ssl_key", ssl_key)
        if ssl_mode is not None:
            pulumi.set(__self__, "ssl_mode", ssl_mode)
        if user is not None:
            pulumi.set(__self__, "user", user)

    @property
    @pulumi.getter(name="awsPrivatelink")
    def aws_privatelink(self) -> Optional[pulumi.Input['ConnectionPostgresAwsPrivatelinkArgs']]:
        """
        The AWS PrivateLink configuration for the Postgres database.
        """
        return pulumi.get(self, "aws_privatelink")

    @aws_privatelink.setter
    def aws_privatelink(self, value: Optional[pulumi.Input['ConnectionPostgresAwsPrivatelinkArgs']]):
        pulumi.set(self, "aws_privatelink", value)

    @property
    @pulumi.getter(name="connectionType")
    def connection_type(self) -> Optional[pulumi.Input[str]]:
        """
        The type of connection.
        """
        return pulumi.get(self, "connection_type")

    @connection_type.setter
    def connection_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "connection_type", value)

    @property
    @pulumi.getter
    def database(self) -> Optional[pulumi.Input[str]]:
        """
        The target Postgres database.
        """
        return pulumi.get(self, "database")

    @database.setter
    def database(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "database", value)

    @property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> Optional[pulumi.Input[str]]:
        """
        The identifier for the connection database.
        """
        return pulumi.get(self, "database_name")

    @database_name.setter
    def database_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "database_name", value)

    @property
    @pulumi.getter
    def host(self) -> Optional[pulumi.Input[str]]:
        """
        The Postgres database hostname.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "host", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The identifier for the connection.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input['ConnectionPostgresPasswordArgs']]:
        """
        The Postgres database password.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input['ConnectionPostgresPasswordArgs']]):
        pulumi.set(self, "password", value)

    @property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[int]]:
        """
        The Postgres database port.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "port", value)

    @property
    @pulumi.getter(name="qualifiedSqlName")
    def qualified_sql_name(self) -> Optional[pulumi.Input[str]]:
        """
        The fully qualified name of the connection.
        """
        return pulumi.get(self, "qualified_sql_name")

    @qualified_sql_name.setter
    def qualified_sql_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "qualified_sql_name", value)

    @property
    @pulumi.getter(name="schemaName")
    def schema_name(self) -> Optional[pulumi.Input[str]]:
        """
        The identifier for the connection schema.
        """
        return pulumi.get(self, "schema_name")

    @schema_name.setter
    def schema_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "schema_name", value)

    @property
    @pulumi.getter(name="sshTunnel")
    def ssh_tunnel(self) -> Optional[pulumi.Input['ConnectionPostgresSshTunnelArgs']]:
        """
        The SSH tunnel configuration for the Postgres database.
        """
        return pulumi.get(self, "ssh_tunnel")

    @ssh_tunnel.setter
    def ssh_tunnel(self, value: Optional[pulumi.Input['ConnectionPostgresSshTunnelArgs']]):
        pulumi.set(self, "ssh_tunnel", value)

    @property
    @pulumi.getter(name="sslCertificate")
    def ssl_certificate(self) -> Optional[pulumi.Input['ConnectionPostgresSslCertificateArgs']]:
        """
        The client certificate for the Postgres database.
        """
        return pulumi.get(self, "ssl_certificate")

    @ssl_certificate.setter
    def ssl_certificate(self, value: Optional[pulumi.Input['ConnectionPostgresSslCertificateArgs']]):
        pulumi.set(self, "ssl_certificate", value)

    @property
    @pulumi.getter(name="sslCertificateAuthority")
    def ssl_certificate_authority(self) -> Optional[pulumi.Input['ConnectionPostgresSslCertificateAuthorityArgs']]:
        """
        The CA certificate for the Postgres database.
        """
        return pulumi.get(self, "ssl_certificate_authority")

    @ssl_certificate_authority.setter
    def ssl_certificate_authority(self, value: Optional[pulumi.Input['ConnectionPostgresSslCertificateAuthorityArgs']]):
        pulumi.set(self, "ssl_certificate_authority", value)

    @property
    @pulumi.getter(name="sslKey")
    def ssl_key(self) -> Optional[pulumi.Input['ConnectionPostgresSslKeyArgs']]:
        """
        The client key for the Postgres database.
        """
        return pulumi.get(self, "ssl_key")

    @ssl_key.setter
    def ssl_key(self, value: Optional[pulumi.Input['ConnectionPostgresSslKeyArgs']]):
        pulumi.set(self, "ssl_key", value)

    @property
    @pulumi.getter(name="sslMode")
    def ssl_mode(self) -> Optional[pulumi.Input[str]]:
        """
        The SSL mode for the Postgres database.
        """
        return pulumi.get(self, "ssl_mode")

    @ssl_mode.setter
    def ssl_mode(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "ssl_mode", value)

    @property
    @pulumi.getter
    def user(self) -> Optional[pulumi.Input['ConnectionPostgresUserArgs']]:
        """
        The Postgres database username.
        """
        return pulumi.get(self, "user")

    @user.setter
    def user(self, value: Optional[pulumi.Input['ConnectionPostgresUserArgs']]):
        pulumi.set(self, "user", value)


class ConnectionPostgres(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 aws_privatelink: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresAwsPrivatelinkArgs']]] = None,
                 database: Optional[pulumi.Input[str]] = None,
                 database_name: Optional[pulumi.Input[str]] = None,
                 host: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresPasswordArgs']]] = None,
                 port: Optional[pulumi.Input[int]] = None,
                 schema_name: Optional[pulumi.Input[str]] = None,
                 ssh_tunnel: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSshTunnelArgs']]] = None,
                 ssl_certificate: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSslCertificateArgs']]] = None,
                 ssl_certificate_authority: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSslCertificateAuthorityArgs']]] = None,
                 ssl_key: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSslKeyArgs']]] = None,
                 ssl_mode: Optional[pulumi.Input[str]] = None,
                 user: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresUserArgs']]] = None,
                 __props__=None):
        """
        The connection resource allows you to manage connections in Materialize.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_materialize as materialize

        # Create a Postgres Connection
        example_postgres_connection = materialize.ConnectionPostgres("examplePostgresConnection",
            database="example",
            host="instance.foo000.us-west-1.rds.amazonaws.com",
            password=materialize.ConnectionPostgresPasswordArgs(
                database_name="database",
                name="example",
                schema_name="schema",
            ),
            port=5432,
            user=materialize.ConnectionPostgresUserArgs(
                secret=materialize.ConnectionPostgresUserSecretArgs(
                    database_name="database",
                    name="example",
                    schema_name="schema",
                ),
            ))
        ```

        ## Import

        #Connections can be imported using the connection id

        ```sh
         $ pulumi import materialize:index/connectionPostgres:ConnectionPostgres example <connection_id>
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresAwsPrivatelinkArgs']] aws_privatelink: The AWS PrivateLink configuration for the Postgres database.
        :param pulumi.Input[str] database: The target Postgres database.
        :param pulumi.Input[str] database_name: The identifier for the connection database.
        :param pulumi.Input[str] host: The Postgres database hostname.
        :param pulumi.Input[str] name: The identifier for the connection.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresPasswordArgs']] password: The Postgres database password.
        :param pulumi.Input[int] port: The Postgres database port.
        :param pulumi.Input[str] schema_name: The identifier for the connection schema.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresSshTunnelArgs']] ssh_tunnel: The SSH tunnel configuration for the Postgres database.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresSslCertificateArgs']] ssl_certificate: The client certificate for the Postgres database.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresSslCertificateAuthorityArgs']] ssl_certificate_authority: The CA certificate for the Postgres database.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresSslKeyArgs']] ssl_key: The client key for the Postgres database.
        :param pulumi.Input[str] ssl_mode: The SSL mode for the Postgres database.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresUserArgs']] user: The Postgres database username.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ConnectionPostgresArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The connection resource allows you to manage connections in Materialize.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_materialize as materialize

        # Create a Postgres Connection
        example_postgres_connection = materialize.ConnectionPostgres("examplePostgresConnection",
            database="example",
            host="instance.foo000.us-west-1.rds.amazonaws.com",
            password=materialize.ConnectionPostgresPasswordArgs(
                database_name="database",
                name="example",
                schema_name="schema",
            ),
            port=5432,
            user=materialize.ConnectionPostgresUserArgs(
                secret=materialize.ConnectionPostgresUserSecretArgs(
                    database_name="database",
                    name="example",
                    schema_name="schema",
                ),
            ))
        ```

        ## Import

        #Connections can be imported using the connection id

        ```sh
         $ pulumi import materialize:index/connectionPostgres:ConnectionPostgres example <connection_id>
        ```

        :param str resource_name: The name of the resource.
        :param ConnectionPostgresArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConnectionPostgresArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 aws_privatelink: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresAwsPrivatelinkArgs']]] = None,
                 database: Optional[pulumi.Input[str]] = None,
                 database_name: Optional[pulumi.Input[str]] = None,
                 host: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresPasswordArgs']]] = None,
                 port: Optional[pulumi.Input[int]] = None,
                 schema_name: Optional[pulumi.Input[str]] = None,
                 ssh_tunnel: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSshTunnelArgs']]] = None,
                 ssl_certificate: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSslCertificateArgs']]] = None,
                 ssl_certificate_authority: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSslCertificateAuthorityArgs']]] = None,
                 ssl_key: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSslKeyArgs']]] = None,
                 ssl_mode: Optional[pulumi.Input[str]] = None,
                 user: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresUserArgs']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConnectionPostgresArgs.__new__(ConnectionPostgresArgs)

            __props__.__dict__["aws_privatelink"] = aws_privatelink
            if database is None and not opts.urn:
                raise TypeError("Missing required property 'database'")
            __props__.__dict__["database"] = database
            __props__.__dict__["database_name"] = database_name
            if host is None and not opts.urn:
                raise TypeError("Missing required property 'host'")
            __props__.__dict__["host"] = host
            __props__.__dict__["name"] = name
            __props__.__dict__["password"] = password
            __props__.__dict__["port"] = port
            __props__.__dict__["schema_name"] = schema_name
            __props__.__dict__["ssh_tunnel"] = ssh_tunnel
            __props__.__dict__["ssl_certificate"] = ssl_certificate
            __props__.__dict__["ssl_certificate_authority"] = ssl_certificate_authority
            __props__.__dict__["ssl_key"] = ssl_key
            __props__.__dict__["ssl_mode"] = ssl_mode
            if user is None and not opts.urn:
                raise TypeError("Missing required property 'user'")
            __props__.__dict__["user"] = user
            __props__.__dict__["connection_type"] = None
            __props__.__dict__["qualified_sql_name"] = None
        super(ConnectionPostgres, __self__).__init__(
            'materialize:index/connectionPostgres:ConnectionPostgres',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            aws_privatelink: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresAwsPrivatelinkArgs']]] = None,
            connection_type: Optional[pulumi.Input[str]] = None,
            database: Optional[pulumi.Input[str]] = None,
            database_name: Optional[pulumi.Input[str]] = None,
            host: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            password: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresPasswordArgs']]] = None,
            port: Optional[pulumi.Input[int]] = None,
            qualified_sql_name: Optional[pulumi.Input[str]] = None,
            schema_name: Optional[pulumi.Input[str]] = None,
            ssh_tunnel: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSshTunnelArgs']]] = None,
            ssl_certificate: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSslCertificateArgs']]] = None,
            ssl_certificate_authority: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSslCertificateAuthorityArgs']]] = None,
            ssl_key: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresSslKeyArgs']]] = None,
            ssl_mode: Optional[pulumi.Input[str]] = None,
            user: Optional[pulumi.Input[pulumi.InputType['ConnectionPostgresUserArgs']]] = None) -> 'ConnectionPostgres':
        """
        Get an existing ConnectionPostgres resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresAwsPrivatelinkArgs']] aws_privatelink: The AWS PrivateLink configuration for the Postgres database.
        :param pulumi.Input[str] connection_type: The type of connection.
        :param pulumi.Input[str] database: The target Postgres database.
        :param pulumi.Input[str] database_name: The identifier for the connection database.
        :param pulumi.Input[str] host: The Postgres database hostname.
        :param pulumi.Input[str] name: The identifier for the connection.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresPasswordArgs']] password: The Postgres database password.
        :param pulumi.Input[int] port: The Postgres database port.
        :param pulumi.Input[str] qualified_sql_name: The fully qualified name of the connection.
        :param pulumi.Input[str] schema_name: The identifier for the connection schema.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresSshTunnelArgs']] ssh_tunnel: The SSH tunnel configuration for the Postgres database.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresSslCertificateArgs']] ssl_certificate: The client certificate for the Postgres database.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresSslCertificateAuthorityArgs']] ssl_certificate_authority: The CA certificate for the Postgres database.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresSslKeyArgs']] ssl_key: The client key for the Postgres database.
        :param pulumi.Input[str] ssl_mode: The SSL mode for the Postgres database.
        :param pulumi.Input[pulumi.InputType['ConnectionPostgresUserArgs']] user: The Postgres database username.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ConnectionPostgresState.__new__(_ConnectionPostgresState)

        __props__.__dict__["aws_privatelink"] = aws_privatelink
        __props__.__dict__["connection_type"] = connection_type
        __props__.__dict__["database"] = database
        __props__.__dict__["database_name"] = database_name
        __props__.__dict__["host"] = host
        __props__.__dict__["name"] = name
        __props__.__dict__["password"] = password
        __props__.__dict__["port"] = port
        __props__.__dict__["qualified_sql_name"] = qualified_sql_name
        __props__.__dict__["schema_name"] = schema_name
        __props__.__dict__["ssh_tunnel"] = ssh_tunnel
        __props__.__dict__["ssl_certificate"] = ssl_certificate
        __props__.__dict__["ssl_certificate_authority"] = ssl_certificate_authority
        __props__.__dict__["ssl_key"] = ssl_key
        __props__.__dict__["ssl_mode"] = ssl_mode
        __props__.__dict__["user"] = user
        return ConnectionPostgres(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="awsPrivatelink")
    def aws_privatelink(self) -> pulumi.Output[Optional['outputs.ConnectionPostgresAwsPrivatelink']]:
        """
        The AWS PrivateLink configuration for the Postgres database.
        """
        return pulumi.get(self, "aws_privatelink")

    @property
    @pulumi.getter(name="connectionType")
    def connection_type(self) -> pulumi.Output[str]:
        """
        The type of connection.
        """
        return pulumi.get(self, "connection_type")

    @property
    @pulumi.getter
    def database(self) -> pulumi.Output[str]:
        """
        The target Postgres database.
        """
        return pulumi.get(self, "database")

    @property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> pulumi.Output[Optional[str]]:
        """
        The identifier for the connection database.
        """
        return pulumi.get(self, "database_name")

    @property
    @pulumi.getter
    def host(self) -> pulumi.Output[str]:
        """
        The Postgres database hostname.
        """
        return pulumi.get(self, "host")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        The identifier for the connection.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def password(self) -> pulumi.Output[Optional['outputs.ConnectionPostgresPassword']]:
        """
        The Postgres database password.
        """
        return pulumi.get(self, "password")

    @property
    @pulumi.getter
    def port(self) -> pulumi.Output[Optional[int]]:
        """
        The Postgres database port.
        """
        return pulumi.get(self, "port")

    @property
    @pulumi.getter(name="qualifiedSqlName")
    def qualified_sql_name(self) -> pulumi.Output[str]:
        """
        The fully qualified name of the connection.
        """
        return pulumi.get(self, "qualified_sql_name")

    @property
    @pulumi.getter(name="schemaName")
    def schema_name(self) -> pulumi.Output[Optional[str]]:
        """
        The identifier for the connection schema.
        """
        return pulumi.get(self, "schema_name")

    @property
    @pulumi.getter(name="sshTunnel")
    def ssh_tunnel(self) -> pulumi.Output[Optional['outputs.ConnectionPostgresSshTunnel']]:
        """
        The SSH tunnel configuration for the Postgres database.
        """
        return pulumi.get(self, "ssh_tunnel")

    @property
    @pulumi.getter(name="sslCertificate")
    def ssl_certificate(self) -> pulumi.Output[Optional['outputs.ConnectionPostgresSslCertificate']]:
        """
        The client certificate for the Postgres database.
        """
        return pulumi.get(self, "ssl_certificate")

    @property
    @pulumi.getter(name="sslCertificateAuthority")
    def ssl_certificate_authority(self) -> pulumi.Output[Optional['outputs.ConnectionPostgresSslCertificateAuthority']]:
        """
        The CA certificate for the Postgres database.
        """
        return pulumi.get(self, "ssl_certificate_authority")

    @property
    @pulumi.getter(name="sslKey")
    def ssl_key(self) -> pulumi.Output[Optional['outputs.ConnectionPostgresSslKey']]:
        """
        The client key for the Postgres database.
        """
        return pulumi.get(self, "ssl_key")

    @property
    @pulumi.getter(name="sslMode")
    def ssl_mode(self) -> pulumi.Output[Optional[str]]:
        """
        The SSL mode for the Postgres database.
        """
        return pulumi.get(self, "ssl_mode")

    @property
    @pulumi.getter
    def user(self) -> pulumi.Output['outputs.ConnectionPostgresUser']:
        """
        The Postgres database username.
        """
        return pulumi.get(self, "user")

