// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package materialize

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCurrentCluster(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetCurrentClusterResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetCurrentClusterResult
	err := ctx.Invoke("materialize:index/getCurrentCluster:GetCurrentCluster", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by GetCurrentCluster.
type GetCurrentClusterResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
}
