// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package materialize

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetTables(ctx *pulumi.Context, args *GetTablesArgs, opts ...pulumi.InvokeOption) (*GetTablesResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetTablesResult
	err := ctx.Invoke("materialize:index/getTables:GetTables", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetTables.
type GetTablesArgs struct {
	// Limit tables to a specific database
	DatabaseName *string `pulumi:"databaseName"`
	// Limit tables to a specific schema within a specific database
	SchemaName *string `pulumi:"schemaName"`
}

// A collection of values returned by GetTables.
type GetTablesResult struct {
	// Limit tables to a specific database
	DatabaseName *string `pulumi:"databaseName"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Limit tables to a specific schema within a specific database
	SchemaName *string `pulumi:"schemaName"`
	// The tables in the account
	Tables []GetTablesTable `pulumi:"tables"`
}

func GetTablesOutput(ctx *pulumi.Context, args GetTablesOutputArgs, opts ...pulumi.InvokeOption) GetTablesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetTablesResult, error) {
			args := v.(GetTablesArgs)
			r, err := GetTables(ctx, &args, opts...)
			var s GetTablesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetTablesResultOutput)
}

// A collection of arguments for invoking GetTables.
type GetTablesOutputArgs struct {
	// Limit tables to a specific database
	DatabaseName pulumi.StringPtrInput `pulumi:"databaseName"`
	// Limit tables to a specific schema within a specific database
	SchemaName pulumi.StringPtrInput `pulumi:"schemaName"`
}

func (GetTablesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTablesArgs)(nil)).Elem()
}

// A collection of values returned by GetTables.
type GetTablesResultOutput struct{ *pulumi.OutputState }

func (GetTablesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTablesResult)(nil)).Elem()
}

func (o GetTablesResultOutput) ToGetTablesResultOutput() GetTablesResultOutput {
	return o
}

func (o GetTablesResultOutput) ToGetTablesResultOutputWithContext(ctx context.Context) GetTablesResultOutput {
	return o
}

// Limit tables to a specific database
func (o GetTablesResultOutput) DatabaseName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetTablesResult) *string { return v.DatabaseName }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetTablesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTablesResult) string { return v.Id }).(pulumi.StringOutput)
}

// Limit tables to a specific schema within a specific database
func (o GetTablesResultOutput) SchemaName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetTablesResult) *string { return v.SchemaName }).(pulumi.StringPtrOutput)
}

// The tables in the account
func (o GetTablesResultOutput) Tables() GetTablesTableArrayOutput {
	return o.ApplyT(func(v GetTablesResult) []GetTablesTable { return v.Tables }).(GetTablesTableArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTablesResultOutput{})
}
