// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Materialize.Outputs
{

    [OutputType]
    public sealed class ConnectionPostgresSslCertificateAuthority
    {
        /// <summary>
        /// The ssl*certificate*authority secret value.
        /// </summary>
        public readonly Outputs.ConnectionPostgresSslCertificateAuthoritySecret? Secret;
        /// <summary>
        /// The ssl*certificate*authority text value.
        /// </summary>
        public readonly string? Text;

        [OutputConstructor]
        private ConnectionPostgresSslCertificateAuthority(
            Outputs.ConnectionPostgresSslCertificateAuthoritySecret? secret,

            string? text)
        {
            Secret = secret;
            Text = text;
        }
    }
}
