// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Materialize.Outputs
{

    [OutputType]
    public sealed class IndexColExpr
    {
        /// <summary>
        /// The name of the option you want to set.
        /// </summary>
        public readonly string Field;
        /// <summary>
        /// The value for the option.
        /// </summary>
        public readonly string? Val;

        [OutputConstructor]
        private IndexColExpr(
            string field,

            string? val)
        {
            Field = field;
            Val = val;
        }
    }
}
