---
version: "3.9"

services:

  materialized:
    image: materialize/materialized:latest
    container_name: materialized
    command:
      - '--cluster-replica-sizes={"3xsmall": {"workers": 1, "scale": 1, "credits_per_hour": "1"}, "2xsmall": {"workers": 1, "scale": 1, "credits_per_hour": "1"}}'
      - --bootstrap-default-cluster-replica-size=3xsmall
      - --bootstrap-builtin-system-cluster-replica-size=3xsmall
      - --bootstrap-builtin-catalog-server-cluster-replica-size=3xsmall
      - --bootstrap-builtin-support-cluster-replica-size=3xsmall
      - --bootstrap-builtin-probe-cluster-replica-size=3xsmall
      - --availability-zone=test1
      - --availability-zone=test2
      - --all-features
    ports:
      - 6875:6875
      - 6877:6877
      - 6878:6878
    healthcheck: {test: curl -f localhost:6878/api/readyz, interval: 1s, start_period: 35s}

  frontegg:
    container_name: frontegg
    build: mocks/frontegg
    ports:
      - "3000:3000"

  cloud:
    container_name: cloud
    build: mocks/cloud
    ports:
      - "3001:3001"
