# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

database: Optional[str]
"""
The Materialize database
"""

host: Optional[str]
"""
Materialize host
"""

password: Optional[str]
"""
Materialize host
"""

port: Optional[int]
"""
The Materialize port number to connect to at the server host
"""

testing: Optional[bool]
"""
Enable to test the provider locally
"""

username: Optional[str]
"""
Materialize username
"""

