// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Materialize.Inputs
{

    public sealed class ConnectionKafkaSaslUsernameArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The sasl*username secret value.
        /// </summary>
        [Input("secret")]
        public Input<Inputs.ConnectionKafkaSaslUsernameSecretArgs>? Secret { get; set; }

        /// <summary>
        /// The sasl_username text value.
        /// </summary>
        [Input("text")]
        public Input<string>? Text { get; set; }

        public ConnectionKafkaSaslUsernameArgs()
        {
        }
        public static new ConnectionKafkaSaslUsernameArgs Empty => new ConnectionKafkaSaslUsernameArgs();
    }
}
