// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Materialize.Inputs
{

    public sealed class SinkKafkaFormatArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Avro format.
        /// </summary>
        [Input("avro")]
        public Input<Inputs.SinkKafkaFormatAvroArgs>? Avro { get; set; }

        /// <summary>
        /// JSON format.
        /// </summary>
        [Input("json")]
        public Input<bool>? Json { get; set; }

        public SinkKafkaFormatArgs()
        {
        }
        public static new SinkKafkaFormatArgs Empty => new SinkKafkaFormatArgs();
    }
}
