// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Materialize.Inputs
{

    public sealed class SinkKafkaFormatAvroGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("avroKeyFullname")]
        public Input<string>? AvroKeyFullname { get; set; }

        [Input("avroValueFullname")]
        public Input<string>? AvroValueFullname { get; set; }

        [Input("schemaRegistryConnection", required: true)]
        public Input<Inputs.SinkKafkaFormatAvroSchemaRegistryConnectionGetArgs> SchemaRegistryConnection { get; set; } = null!;

        public SinkKafkaFormatAvroGetArgs()
        {
        }
        public static new SinkKafkaFormatAvroGetArgs Empty => new SinkKafkaFormatAvroGetArgs();
    }
}
