name: test
on:
  pull_request:
    paths:
      - provider/**
      - examples/**
      - .github/workflows/**

env:
  MZ_HOST: localhost
  MZ_USER: mz_system
  MZ_SSLMODE: disable
  MZ_PORT: 6877
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl

      - run: make build_python

      - run: docker-compose -f examples/docker-compose.yml up -d --build

      - run: make test

      - run: docker compose -f examples/docker-compose.yml down