name: test

on:
  pull_request:
    paths:
      - provider/**
      - examples/**
      - .github/workflows/**

env:
  MZ_HOST: localhost
  MZ_USER: mz_system
  MZ_SSLMODE: disable
  MZ_PORT: 6877
  PYTHONVERSION: 3.9
  GOVERSION: 1.21.x

jobs: 
  test:
    name: acceptance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/checkout/issues/290
      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOVERSION }}

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHONVERSION }}

      - uses: pulumi/action-install-pulumi-cli@v2

      - run: make build_python

      - run: docker-compose -f examples/docker-compose.yml up -d --build

      - run: make test

      - run: docker compose -f examples/docker-compose.yml down