// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as materialize from "@pulumi/materialize";
 *
 * const all = pulumi.output(materialize.GetIndexes());
 * const materializeGetIndexes = pulumi.output(materialize.GetIndexes({
 *     databaseName: "materialize",
 * }));
 * const materializeSchema = pulumi.output(materialize.GetIndexes({
 *     databaseName: "materialize",
 *     schemaName: "schema",
 * }));
 * ```
 */
export function getIndexes(args?: GetIndexesArgs, opts?: pulumi.InvokeOptions): Promise<GetIndexesResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("materialize:index/getIndexes:GetIndexes", {
        "databaseName": args.databaseName,
        "schemaName": args.schemaName,
    }, opts);
}

/**
 * A collection of arguments for invoking GetIndexes.
 */
export interface GetIndexesArgs {
    /**
     * Limit indexes to a specific database
     */
    databaseName?: string;
    /**
     * Limit indexes to a specific schema within a specific database
     */
    schemaName?: string;
}

/**
 * A collection of values returned by GetIndexes.
 */
export interface GetIndexesResult {
    /**
     * Limit indexes to a specific database
     */
    readonly databaseName?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The indexes in the account
     */
    readonly indexes: outputs.GetIndexesIndex[];
    /**
     * Limit indexes to a specific schema within a specific database
     */
    readonly schemaName?: string;
}

export function getIndexesOutput(args?: GetIndexesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIndexesResult> {
    return pulumi.output(args).apply(a => getIndexes(a, opts))
}

/**
 * A collection of arguments for invoking GetIndexes.
 */
export interface GetIndexesOutputArgs {
    /**
     * Limit indexes to a specific database
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Limit indexes to a specific schema within a specific database
     */
    schemaName?: pulumi.Input<string>;
}
