// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A secret securely stores sensitive credentials (like passwords and SSL keys) in Materialize’s secret management system.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as materialize from "@pulumi/materialize";
 *
 * const exampleSecret = new materialize.Secret("example_secret", {
 *     value: "some-secret-value",
 * });
 * ```
 *
 * ## Import
 *
 * # Secrets can be imported using the secret id
 *
 * ```sh
 *  $ pulumi import materialize:index/secret:Secret example_secret <secret_id>
 * ```
 */
export class Secret extends pulumi.CustomResource {
    /**
     * Get an existing Secret resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretState, opts?: pulumi.CustomResourceOptions): Secret {
        return new Secret(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/secret:Secret';

    /**
     * Returns true if the given object is an instance of Secret.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Secret {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Secret.__pulumiType;
    }

    /**
     * The identifier for the secret database.
     */
    public readonly databaseName!: pulumi.Output<string | undefined>;
    /**
     * The identifier for the secret.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The fully qualified name of the secret.
     */
    public /*out*/ readonly qualifiedSqlName!: pulumi.Output<string>;
    /**
     * The identifier for the secret schema.
     */
    public readonly schemaName!: pulumi.Output<string | undefined>;
    /**
     * The value for the secret. The value expression may not reference any relations, and must be a bytea string literal.
     */
    public readonly value!: pulumi.Output<string | undefined>;

    /**
     * Create a Secret resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SecretArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretArgs | SecretState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretState | undefined;
            resourceInputs["databaseName"] = state ? state.databaseName : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["qualifiedSqlName"] = state ? state.qualifiedSqlName : undefined;
            resourceInputs["schemaName"] = state ? state.schemaName : undefined;
            resourceInputs["value"] = state ? state.value : undefined;
        } else {
            const args = argsOrState as SecretArgs | undefined;
            resourceInputs["databaseName"] = args ? args.databaseName : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["schemaName"] = args ? args.schemaName : undefined;
            resourceInputs["value"] = args ? args.value : undefined;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Secret.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Secret resources.
 */
export interface SecretState {
    /**
     * The identifier for the secret database.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * The identifier for the secret.
     */
    name?: pulumi.Input<string>;
    /**
     * The fully qualified name of the secret.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The identifier for the secret schema.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The value for the secret. The value expression may not reference any relations, and must be a bytea string literal.
     */
    value?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Secret resource.
 */
export interface SecretArgs {
    /**
     * The identifier for the secret database.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * The identifier for the secret.
     */
    name?: pulumi.Input<string>;
    /**
     * The identifier for the secret schema.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The value for the secret. The value expression may not reference any relations, and must be a bytea string literal.
     */
    value?: pulumi.Input<string>;
}
